[build]
  command = "npm install"
  publish = "public"
  functions = "functions-build"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200